file_format: "1"
id: heartbreak
name: Heartbreak
type: shield
url: https://github.com/nnandrew/heartbreak/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
  - encoder
siblings:
  - heartbreak_left
  - heartbreak_right
